# Here are some test HTTP requests to send to the ESP32. Give it a few seconds to startup before sending requests.

#####
http://<esp32_ip>/update?output=fan&state=off

#####
http://<esp32_ip>/update?output=mode&state=manual

#####
http://<esp32_ip>/update?output=toggle_wait_time&state=5000

#####
http://<esp32_ip>/status?var=temp

#####
http://<esp32_ip>/status?var=humidity

#####
http://<esp32_ip>/status?var=dewpoint

#####
http://<esp32_ip>/status?var=fan

#####
http://<esp32_ip>/status?var=dew

#####
http://<esp32_ip>/status?var=wait_time

#####
http://<esp32_ip>/status?var=toggle_wait_time

#####
http://<esp32_ip>/status?var=cooling_fan_threshold

#####
http://<esp32_ip>/status?var=cooling_fan_abs_threshold

#####
http://<esp32_ip>/status?var=dew_heater_threshold

#####
http://<esp32_ip>/status?var=dew_heater_abs_threshold

#####
http://<esp32_ip>/status?var=mode

#####
http://<esp32_ip>/status?var=all